version: '3.9'
services:
  dev:
    image: akraradets/vue:v0.0.1
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./project:/root/project
      - ./docs:/root/docs
      - node_modules:/root/project/node_modules
      - vscode-dev:/root/.vscode-server

volumes:
  vscode-dev:
  node_modules: